### ISSUE TITLE
Getting legacy package of pfBlockerNG 

### ISSUE THREAD

**Issue by Ivanich41** [EvergreenCartoons/SenselessViolence#6]
Hello, I am writing CVE reports for my university and I am interested at that one. But unfortunatly I could not find required package in google. There is only 2.1.4_28 version in package manager:
![image](https://user-images.githubusercontent.com/77790965/191347019-14ab61f3-3a1b-44be-876f-40642cd5c269.png)

Where should i look for the right one? Thanks in advance

**Comment by EvergreenCartoons** [comment]
`wget https://files01.netgate.com/pkg/pfSense_plus-v21_09_amd64-pfSense_plus_v21_09/All/pfSense-pkg-pfBlockerNG-2.1.4_26.pkg`

You can install it with `pkg add`, though you must also install the dependencies.

I'll upload a copy to the git repo later.

**Comment by EvergreenCartoons** [comment]
@Ivanich41 I also put archival copy here: https://github.com/EvergreenCartoons/SenselessViolence/tree/main/archive :)

**Comment by Ivanich41** [comment]
Much thanks!
